### ISSUE TITLE
Auto-Grouping

### ISSUE THREAD

**Issue by SriPallaviDamuluri** [chandur626/ClassMateBot#12]
Automatically assign groups for people that are not already in a group.
Set up a timer from the start of class and automatically assign groups after a certain time period

**Comment by HariniBharata** [comment]
@SriPallaviDamuluri can we also implement find groups?

**Comment by SriPallaviDamuluri** [comment]
> @SriPallaviDamuluri can we also implement find groups?

Implemented part of find-group branch.

**Comment by SriPallaviDamuluri** [comment]
Merged to main - https://github.com/chandur626/ClassMateBot/pull/22
