### ISSUE TITLE
Email Attachment

### ISSUE THREAD

**Issue by chandur626** [chandur626/ClassMateBot#8]
Email user a file attachment when user gives a thums up reaction for the file.

**Comment by nirajlavani** [comment]
Does emailing attachments activate on just thumbs up or other emojis?

**Comment by chandur626** [comment]
emailing attachments get activated on white-heavy-mark. I thought it's not a good idea to have that activated on all emojis.

**Comment by chandur626** [comment]
Pull request related to this issue has been merged. https://github.com/chandur626/ClassMateBot/pull/24
